INSERT INTO main_dictionary(eng_word, ukr_word) VALUES ('cat', N'кiт'), ('dog', N'собака'), ('mouse', N'миша'),
('classroom', N'клас'),
('book', N'книга'),
('pen', N'ручка'),
('bag', N'рюкзак'),
('pencil', N'олiвець'),
('chair', N'стiлець'),
('blackboard', N'дошка'),
('family', N'сiм''я'),
('father', N'тато'),
('mother', N'мама'),
('brother', N'брат'),
('sister', N'сестра'),
('grandmother', N'бабуся'),
('grandfather', N'дiдусь'),
('pony', N'понi'),
('bird', N'пташка'),
('parrot', N'папуга'),
('fish', N'риба'),
('rabbit', N'кролик'),
('jeans', N'джинси'),
('jam', N'джем'),
('juice', N'сiк'),
('happy', N'щасливий'),
('sad', N'сумний'),
('angry', N'злий'),
('hungry', N'голодний'),
('thirsty', N'спраглий'),
('big', N'великий'),
('small', N'маленький'),
('fat', N'товстий'),
('thin', N'тонкий'),
('tall', N'високий'),
('short', N'короткий'),
('hot', N'гарячий'),
('hand', N'рука'),
('apple', N'яблуко'),
('boy', N'хлопчик'),
('doll', N'лялька'),
('clock', N'годинник'),
('cake', N'тiстечко'),
('duck', N'качка'),
('ear', N'вухо'),
('elephant', N'слон'),
('egg', N'яйце'),
('frog', N'жаба'),
('flower', N'квiтка'),
('glass', N'скло'),
('girl', N'дiвчинка'),
('goose', N'гусак'),
('head', N'голова'),
('house', N'будинок'),
('hen', N'курка'),
('island', N'острiв'),
('kite', N'повiтряний змiй'),
('bike', N'велосипед'),
('snake', N'змiя'),
('lemon', N'лимон'),
('lion', N'лев'),
('lamp', N'лампа'),
('monkey', N'мавпа'),
('moon', N'мiсяць'),
('nose', N'нiс'),
('nest', N'гнiздо'),
('nine', N'дев''ять'),
('pig', N'свиня'),
('Ukraine', N'Укра?на'),
('umbrella', N'парасолька'),
('can', N'можу, вмiти'),
('he', N'вiн'),
('she', N'вона'),
('it', N'воно'),
('run', N'бiгти'),
('jump', N'стрибати'),
('fly', N'лiтати, муха'),
('carrots', N'морква'),
('rice', N'рис'),
('beans', N'квасоля'),
('fruit', N'фрукт'),
('banana', N'банан'),
('grape', N'виноград'),
('strawberry', N'полуниця'),
('orange', N'апельсин, помаранчевий'),
('key', N'ключ'),
('queen', N'королева'),
('question', N'питання'),
('squirrel', N'бiлка'),
('rose', N'троянда'),
('rain', N'дощ'),
('ship', N'корабель'),
('sun', N'сонце'),
('school', N'школа'),
('train', N'потяг'),
('tree', N'дерево'),
('table', N'стiл'),
('bus', N'автобус'),
('volleyball', N'волейбол'),
('violin', N'скрипка'),
('vase', N'ваза'),
('well', N'добре, колодязь'),
('watch', N'годинник'),
('window', N'вiкно'),
('fox', N'лисиця'),
('box', N'коробка'),
('baby', N'немовля'),
('yacht', N'яхта'),
('zero', N'нуль'),
('zipper', N'застiбка'),
('zebra', N'зебра'),
('in', N'в'),
('shoes', N'туфлi, черевики'),
('shirt', N'сорочка'),
('on', N'на'),
('under', N'пiд'),
('bed', N'лiжко'),
('wardrobe', N'шафа'),
('kitchen', N'кухня'),
('bedroom', N'спальня'),
('bathroom', N'вана кiмната'),
('living room', N'вiтальня'),
('sofa', N'диван'),
('meat', N'м''ясо'),
('pie', N'пирiг'),
('Italy', N'Iталiя'),
('China', N' итай'),
('white', N'бiлий'),
('black', N'чорний'),
('red', N'червоний'),
('yellow', N'жовтий'),
('green', N'зелений'),
('blue', N'синiй'),
('purple', N'фiолетовий'),
('pink', N'рожевий'),
('brown', N'коричневий'),
('grey', N'сiрий'),
('pencil case', N'пенал'),
('teacher', N'вчитель'),
('close', N'зачинено, закривати'),
('open', N'вiдкривати'),
('point', N'показати'),
('sit', N'сидiти'),
('lollipop', N'льодяник'),
('balloon', N'надувна кулька'),
('give', N'давати'),
('present', N'подарунок'),
('card', N'листiвка'),
('ruler', N'лiнiйка'),
('kid', N'дитина'),
('welcome', N'ласкаво просимо'),
('star', N'зiрка'),
('teddy bear', N'плюшевий ведмедик'),
('make breakfast', N'робити снiданок'),
('thank you', N'дякую'),
('please', N'будь ласка'),
('sorry', N'вибачте'),
('animal', N'тварина'),
('sheep', N'вiвця'),
('camel', N'верблюд'),
('turtle', N'черепаха'),
('cow', N'корова'),
('hedgehog', N'?жак'),
('wolf', N'вовк'),
('one', N'один'),
('two', N'два'),
('three', N'три'),
('four', N'чотири'),
('five', N'п''ять'),
('six', N'шiсть'),
('seven', N'сiм'),
('eight', N'вiсiм'),
('ten', N'десять'),
('repeat', N'повторити'),
('sing', N'спiвати'),
('say', N'казати'),
('play', N'грати'),
('sit down', N'сiсти'),
('stand up', N'встати'),
('friend', N'друг'),
('hug', N'обiйняти, обiймати'),
('his', N'його'),
('her', N'??'),
('I', N'я'),
('you', N'ти'),
('we', N'ми'),
('my', N'мiй (моЇ)'),
('ice cream', N'морозиво'),
('plane', N'лiтак'),
('Monday', N'понедiлок'),
('Tuesday', N'вiвторок'),
('Wednesday', N'середа'),
('Thursday', N'четвер'),
('Friday', N'п''ятниця'),
('Saturday', N'субота'),
('Sunday', N'недiля'),
('January', N'сiчень'),
('February', N'лютий'),
('March', N'березень'),
('April', N'квiтень'),
('May', N'травень'),
('June', N'червень'),
('July', N'липень'),
('August', N'серпень'),
('September', N'вересень'),
('October', N'жовтень'),
('November', N'листопад'),
('December', N'грудень')