INSERT INTO main_dictionary(eng_word, ukr_word) VALUES ('cat', N'кіт'), ('dog', N'собака'), ('mouse', N'миша'),
('classroom', N'клас'),
('book', N'книга'),
('pen', N'ручка'),
('bag', N'рюкзак'),
('pencil', N'олівець'),
('chair', N'стілець'),
('blackboard', N'дошка'),
('family', N'сім''я'),
('father', N'тато'),
('mother', N'мама'),
('brother', N'брат'),
('sister', N'сестра'),
('grandmother', N'бабуся'),
('grandfather', N'дідусь'),
('pony', N'поні'),
('bird', N'пташка'),
('parrot', N'папуга'),
('fish', N'риба'),
('rabbit', N'кролик'),
('jeans', N'джинси'),
('jam', N'джем'),
('juice', N'сік'),
('happy', N'щасливий'),
('sad', N'сумний'),
('angry', N'злий'),
('hungry', N'голодний'),
('thirsty', N'спраглий'),
('big', N'великий'),
('small', N'маленький'),
('fat', N'товстий'),
('thin', N'тонкий'),
('tall', N'високий'),
('short', N'короткий'),
('hot', N'гарячий'),
('hand', N'рука'),
('apple', N'яблуко'),
('boy', N'хлопчик'),
('doll', N'лялька'),
('clock', N'годинник'),
('cake', N'тістечко'),
('duck', N'качка'),
('ear', N'вухо'),
('elephant', N'слон'),
('egg', N'яйце'),
('frog', N'жаба'),
('flower', N'квітка'),
('glass', N'скло'),
('girl', N'дівчинка'),
('goose', N'гусак'),
('head', N'голова'),
('house', N'будинок'),
('hen', N'курка'),
('island', N'острів'),
('kite', N'повітряний змій'),
('bike', N'велосипед'),
('snake', N'змія'),
('lemon', N'лимон'),
('lion', N'лев'),
('lamp', N'лампа'),
('monkey', N'мавпа'),
('moon', N'місяць'),
('nose', N'ніс'),
('nest', N'гніздо'),
('nine', N'дев''ять'),
('pig', N'свиня'),
('Ukraine', N'Україна'),
('umbrella', N'парасолька'),
('can', N'можу, вміти'),
('he', N'він'),
('she', N'вона'),
('it', N'воно'),
('run', N'бігти'),
('jump', N'стрибати'),
('fly', N'літати, муха'),
('carrots', N'морква'),
('rice', N'рис'),
('eggs', N'яйця'),
('beans', N'квасоля'),
('fruit', N'фрукт'),
('banana', N'банан'),
('grape', N'виноград'),
('strawberry', N'полуниця'),
('orange', N'апельсин, помаранчевий'),
('key', N'ключ'),
('queen', N'королева'),
('question', N'питання'),
('squirrel', N'білка'),
('rose', N'троянда'),
('rain', N'дощ'),
('ship', N'корабель'),
('sun', N'сонце'),
('school', N'школа'),
('train', N'потяг'),
('tree', N'дерево'),
('table', N'стіл'),
('bus', N'автобус'),
('volleyball', N'волейбол'),
('violin', N'скрипка'),
('vase', N'ваза'),
('well', N'добре, колодязь'),
('watch', N'годинник'),
('window', N'вікно'),
('fox', N'лисиця'),
('box', N'коробка'),
('baby', N'немовля'),
('yacht', N'яхта'),
('zero', N'нуль'),
('zipper', N'застібка'),
('zebra', N'зебра'),
('in', N'в'),
('shoes', N'туфлі, черевики'),
('shirt', N'сорочка'),
('on', N'на'),
('under', N'під'),
('bed', N'ліжко'),
('wardrobe', N'шафа'),
('kitchen', N'кухня'),
('bedroom', N'спальня'),
('bathroom', N'вана кімната'),
('living room', N'вітальня'),
('sofa', N'диван'),
('meat', N'м''ясо'),
('pie', N'пиріг'),
('Italy', N'Iталія'),
('China', N'Китай'),
('white', N'білий'),
('black', N'чорний'),
('red', N'червоний'),
('yellow', N'жовтий'),
('green', N'зелений'),
('blue', N'синій'),
('purple', N'фіолетовий'),
('pink', N'рожевий'),
('brown', N'коричневий'),
('grey', N'сірий'),
('pencil case', N'пенал'),
('teacher', N'вчитель'),
('close', N'зачинено, закривати'),
('open', N'відкривати'),
('point', N'показати'),
('sit', N'сидіти'),
('lollipop', N'льодяник'),
('balloon', N'надувна кулька'),
('give', N'давати'),
('present', N'подарунок'),
('card', N'листівка'),
('ruler', N'лінійка'),
('kid', N'дітина'),
('welcome', N'ласкаво просимо'),
('star', N'зірка'),
('teddy bear', N'плюшевий ведмедик'),
('make breakfast', N'робити сніданок'),
('thank you', N'дякую'),
('please', N'будь ласка'),
('sorry', N'вибачте'),
('animal', N'тварина'),
('sheep', N'вівця'),
('camel', N'верблюд'),
('turtle', N'черепаха'),
('cow', N'корова'),
('hedgehog', N'їжак'),
('wolf', N'вовк'),
('one', N'один'),
('two', N'два'),
('three', N'три'),
('four', N'чотири'),
('five', N'п''ять'),
('six', N'шість'),
('seven', N'сім'),
('eight', N'вісім'),
('ten', N'десять'),
('repeat', N'повторити'),
('sing', N'співати'),
('say', N'казати'),
('play', N'грати'),
('sit down', N'сісти'),
('stand up', N'встати'),
('friend', N'друг'),
('hug', N'обійняти, обіймати'),
('his', N'його'),
('her', N'її'),
('I', N'я'),
('you', N'ти'),
('we', N'ми'),
('my', N'мій (моє)'),
('ice cream', N'морозиво'),
('plane', N'літак'),
('Monday', N'понеділок'),
('Tuesday', N'вівторок'),
('Wednesday', N'середа'),
('Thursday', N'четвер'),
('Friday', N'п''ятниця'),
('Saturday', N'субота'),
('Sunday', N'неділя'),
('January', N'січень'),
('February', N'лютий'),
('March', N'березень'),
('April', N'квітень'),
('May', N'травень'),
('June', N'червень'),
('July', N'липень'),
('August', N'серпень'),
('September', N'вересень'),
('October', N'жовтень'),
('November', N'листопад'),
('December', N'грудень')