INSERT INTO main_dictionary(eng_word, ukr_word) VALUES ('cat', N'к≥т'), ('dog', N'собака'), ('mouse', N'миша'),
('classroom', N'клас'),
('book', N'книга'),
('pen', N'ручка'),
('bag', N'рюкзак'),
('pencil', N'ол≥вець'),
('chair', N'ст≥лець'),
('blackboard', N'дошка'),
('family', N'с≥м''€'),
('father', N'тато'),
('mother', N'мама'),
('brother', N'брат'),
('sister', N'сестра'),
('grandmother', N'бабус€'),
('grandfather', N'д≥дусь'),
('pony', N'пон≥'),
('bird', N'пташка'),
('parrot', N'папуга'),
('fish', N'риба'),
('rabbit', N'кролик'),
('jeans', N'джинси'),
('jam', N'джем'),
('juice', N'с≥к'),
('happy', N'щасливий'),
('sad', N'сумний'),
('angry', N'злий'),
('hungry', N'голодний'),
('thirsty', N'спраглий'),
('big', N'великий'),
('small', N'маленький'),
('fat', N'товстий'),
('thin', N'тонкий'),
('tall', N'високий'),
('short', N'короткий'),
('hot', N'гар€чий'),
('hand', N'рука'),
('apple', N'€блуко'),
('boy', N'хлопчик'),
('doll', N'л€лька'),
('clock', N'годинник'),
('cake', N'т≥стечко'),
('duck', N'качка'),
('ear', N'вухо'),
('elephant', N'слон'),
('egg', N'€йце'),
('frog', N'жаба'),
('flower', N'кв≥тка'),
('glass', N'скло'),
('girl', N'д≥вчинка'),
('goose', N'гусак'),
('head', N'голова'),
('house', N'будинок'),
('hen', N'курка'),
('island', N'остр≥в'),
('kite', N'пов≥тр€ний зм≥й'),
('bike', N'велосипед'),
('snake', N'зм≥€'),
('lemon', N'лимон'),
('lion', N'лев'),
('lamp', N'лампа'),
('monkey', N'мавпа'),
('moon', N'м≥с€ць'),
('nose', N'н≥с'),
('nest', N'гн≥здо'),
('nine', N'дев''€ть'),
('pig', N'свин€'),
('Ukraine', N'”крањна'),
('umbrella', N'парасолька'),
('can', N'можу, вм≥ти'),
('he', N'в≥н'),
('she', N'вона'),
('it', N'воно'),
('run', N'б≥гти'),
('jump', N'стрибати'),
('fly', N'л≥тати, муха'),
('carrots', N'морква'),
('rice', N'рис'),
('eggs', N'€йц€'),
('beans', N'квасол€'),
('fruit', N'фрукт'),
('banana', N'банан'),
('grape', N'виноград'),
('strawberry', N'полуниц€'),
('orange', N'апельсин, помаранчевий'),
('key', N'ключ'),
('queen', N'королева'),
('question', N'питанн€'),
('squirrel', N'б≥лка'),
('rose', N'тро€нда'),
('rain', N'дощ'),
('ship', N'корабель'),
('sun', N'сонце'),
('school', N'школа'),
('train', N'пот€г'),
('tree', N'дерево'),
('table', N'ст≥л'),
('bus', N'автобус'),
('volleyball', N'волейбол'),
('violin', N'скрипка'),
('vase', N'ваза'),
('well', N'добре, колод€зь'),
('watch', N'годинник'),
('window', N'в≥кно'),
('fox', N'лисиц€'),
('box', N'коробка'),
('baby', N'немовл€'),
('yacht', N'€хта'),
('zero', N'нуль'),
('zipper', N'заст≥бка'),
('zebra', N'зебра'),
('in', N'в'),
('shoes', N'туфл≥, черевики'),
('shirt', N'сорочка'),
('on', N'на'),
('under', N'п≥д'),
('bed', N'л≥жко'),
('wardrobe', N'шафа'),
('kitchen', N'кухн€'),
('bedroom', N'спальн€'),
('bathroom', N'вана к≥мната'),
('living room', N'в≥тальн€'),
('sofa', N'диван'),
('meat', N'м''€со'),
('pie', N'пир≥г'),
('Italy', N'Iтал≥€'),
('China', N' итай'),
('white', N'б≥лий'),
('black', N'чорний'),
('red', N'червоний'),
('yellow', N'жовтий'),
('green', N'зелений'),
('blue', N'син≥й'),
('purple', N'ф≥олетовий'),
('pink', N'рожевий'),
('brown', N'коричневий'),
('grey', N'с≥рий'),
('pencil case', N'пенал'),
('teacher', N'вчитель'),
('close', N'зачинено, закривати'),
('open', N'в≥дкривати'),
('point', N'показати'),
('sit', N'сид≥ти'),
('lollipop', N'льод€ник'),
('balloon', N'надувна кулька'),
('give', N'давати'),
('present', N'подарунок'),
('card', N'лист≥вка'),
('ruler', N'л≥н≥йка'),
('kid', N'д≥тина'),
('welcome', N'ласкаво просимо'),
('star', N'з≥рка'),
('teddy bear', N'плюшевий ведмедик'),
('make breakfast', N'робити сн≥данок'),
('thank you', N'д€кую'),
('please', N'будь ласка'),
('sorry', N'вибачте'),
('animal', N'тварина'),
('sheep', N'в≥вц€'),
('camel', N'верблюд'),
('turtle', N'черепаха'),
('cow', N'корова'),
('hedgehog', N'њжак'),
('wolf', N'вовк'),
('one', N'один'),
('two', N'два'),
('three', N'три'),
('four', N'чотири'),
('five', N'п''€ть'),
('six', N'ш≥сть'),
('seven', N'с≥м'),
('eight', N'в≥с≥м'),
('ten', N'дес€ть'),
('repeat', N'повторити'),
('sing', N'сп≥вати'),
('say', N'казати'),
('play', N'грати'),
('sit down', N'с≥сти'),
('stand up', N'встати'),
('friend', N'друг'),
('hug', N'об≥йн€ти, об≥ймати'),
('his', N'його'),
('her', N'њњ'),
('I', N'€'),
('you', N'ти'),
('we', N'ми'),
('my', N'м≥й (моЇ)'),
('ice cream', N'морозиво'),
('plane', N'л≥так'),
('Monday', N'понед≥лок'),
('Tuesday', N'в≥второк'),
('Wednesday', N'середа'),
('Thursday', N'четвер'),
('Friday', N'п''€тниц€'),
('Saturday', N'субота'),
('Sunday', N'нед≥л€'),
('January', N'с≥чень'),
('February', N'лютий'),
('March', N'березень'),
('April', N'кв≥тень'),
('May', N'травень'),
('June', N'червень'),
('July', N'липень'),
('August', N'серпень'),
('September', N'вересень'),
('October', N'жовтень'),
('November', N'листопад'),
('December', N'грудень')