"""init

Revision ID: e37db67571cc
Revises:
Create Date: 2026-08-30 13:47:16.181869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e37db67571cc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "main_dictionary",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("eng_word", sa.String(length=100), nullable=False),
        sa.Column("ukr_word", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_name", sa.Unicode(length=100), nullable=True),
        sa.Column(
            "telegram_first_name", sa.Unicode(length=100), nullable=True
        ),
        sa.Column("telegram_last_name", sa.Unicode(length=100), nullable=True),
        sa.Column("is_sync", sa.Boolean(), nullable=False),
        sa.Column("last_article_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_article_id"],
            ["main_dictionary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.create_table(
        "user_articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["main_dictionary.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_articles")
    op.drop_table("users")
    op.drop_table("main_dictionary")
    # ### end Alembic commands ###
